import React, { useState, useEffect } from 'react';
import { DraftBooking } from '../types';

interface LiveBookingPanelProps {
  draft: DraftBooking;
}

const FieldLabel = ({ children }: { children?: React.ReactNode }) => (
  <label className="text-[10px] uppercase font-black text-stone-400 block mb-2 tracking-[0.2em]">{children}</label>
);

const PhysicalReceiptModal = ({ draft, onClose }: { draft: DraftBooking, onClose: () => void }) => (
  <div className="fixed inset-0 z-[400] flex items-center justify-center p-6 animate-fade-in">
    <div className="absolute inset-0 bg-navy-950/90 backdrop-blur-xl" onClick={onClose}></div>
    <div className="relative bg-[#FFFEFA] w-full max-w-lg p-12 shadow-[0_50px_100px_rgba(0,0,0,0.8)] flex flex-col items-center text-stone-800 font-serif border-t-[16px] border-gold-500 rounded-sm animate-float overflow-hidden">
      <div className="absolute inset-0 opacity-10 bg-[url('https://www.transparenttextures.com/patterns/natural-paper.png')] pointer-events-none"></div>
      
      <div className="absolute top-4 right-4 print:hidden">
        <button onClick={onClose} className="w-10 h-10 flex items-center justify-center text-stone-300 hover:text-navy-900 hover:bg-stone-100 rounded-full transition-all">&times;</button>
      </div>
      
      <div className="text-center mb-12 relative z-10">
        <span className="text-gold-500 text-4xl mb-4 block">⚜</span>
        <h2 className="text-4xl font-black tracking-[0.2em] uppercase mb-2 text-navy-950">Grand Horizon</h2>
        <p className="text-[10px] uppercase tracking-[0.5em] text-gold-600 font-bold">Official Physical Confirmation</p>
      </div>

      <div className="w-full space-y-8 border-y-2 py-10 border-stone-200/50 relative z-10">
        <div className="flex justify-between items-baseline gap-4">
          <span className="uppercase tracking-[0.2em] text-[9px] font-black text-stone-400">Confirmation ID</span>
          <span className="font-bold text-navy-900 font-mono text-sm tracking-widest">{draft.bookingId || 'HZN-9281'}</span>
        </div>
        <div className="flex justify-between items-baseline gap-4">
          <span className="uppercase tracking-[0.2em] text-[9px] font-black text-stone-400">Guest Principal</span>
          <span className="text-xl font-bold text-navy-950">{draft.guestName || 'Valued Resident'}</span>
        </div>
        <div className="flex justify-between items-baseline gap-4">
          <span className="uppercase tracking-[0.2em] text-[9px] font-black text-stone-400">Residency Window</span>
          <span className="font-bold text-navy-900">{draft.checkIn} — {draft.checkOut}</span>
        </div>
        <div className="flex justify-between items-baseline gap-4">
          <span className="uppercase tracking-[0.2em] text-[9px] font-black text-stone-400">Selected Residence</span>
          <span className="font-bold text-navy-900 italic">{draft.roomType}</span>
        </div>
        <div className="pt-8 border-t border-dashed border-stone-200 flex justify-between items-end">
          <div className="flex flex-col">
            <span className="uppercase tracking-[0.2em] text-[9px] font-black text-stone-400 mb-1">Accounting Total</span>
            <span className="text-[9px] text-stone-400">All applicable taxes included</span>
          </div>
          <span className="text-5xl font-black text-navy-950 tracking-tighter">${draft.total?.toLocaleString()}</span>
        </div>
      </div>

      <div className="mt-12 text-center relative z-10">
        <p className="text-[9px] uppercase tracking-[0.3em] text-stone-400 leading-loose mb-8">
          This document is generated by the Horizon Palace AI Protocol.<br />
          Present this physical record at the Grand Foyer for Priority Check-in.<br />
          A digital duplicate has been routed to your private inbox.
        </p>
        <div className="w-24 h-24 mx-auto opacity-10 grayscale brightness-0 contrast-200">
           <img src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=GRANDHORIZON" alt="Security QR" className="w-full h-full" />
        </div>
      </div>

      <div className="flex gap-4 mt-10 print:hidden relative z-10 w-full">
        <button onClick={() => window.print()} className="flex-1 px-8 py-4 bg-navy-950 text-white text-[10px] font-black uppercase tracking-[0.2em] rounded-full hover:bg-gold-500 transition-all shadow-2xl active:scale-95">
          Print Confirmation
        </button>
        <button onClick={onClose} className="px-8 py-4 bg-stone-100 text-stone-500 text-[10px] font-black uppercase tracking-[0.2em] rounded-full hover:bg-stone-200 transition-all">
          Close
        </button>
      </div>
    </div>
  </div>
);

const LiveBookingPanel: React.FC<LiveBookingPanelProps> = ({ draft }) => {
  const [showPhysical, setShowPhysical] = useState(false);
  const [lastUpdate, setLastUpdate] = useState<string | null>(null);

  useEffect(() => {
    setLastUpdate(new Date().toLocaleTimeString());
  }, [draft.guestName, draft.checkIn, draft.checkOut, draft.roomType, draft.total]);

  // Determine the status label
  const isComplete = draft.guestName && draft.checkIn && draft.checkOut && draft.roomType && draft.guests;
  const statusLabel = draft.status === 'confirmed' 
    ? 'Booking Confirmed' 
    : isComplete 
      ? 'Listening for Confirmation...' 
      : 'Draft Booking';

  return (
    <div className="w-full h-full bg-white rounded-[2.5rem] shadow-2xl border border-stone-100 overflow-hidden flex flex-col animate-fade-in-up transform transition-all duration-500">
      {showPhysical && <PhysicalReceiptModal draft={draft} onClose={() => setShowPhysical(false)} />}
      
      {/* Dynamic Sync Header */}
      <div className="bg-navy-950 p-8 text-white text-center relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-gold-300 via-gold-500 to-gold-300"></div>
        <div className="relative z-10">
            <h3 className="font-serif font-bold tracking-[0.3em] text-gold-100 uppercase text-xs mb-2">Live Concierge Synchronizing</h3>
            <div className="flex items-center justify-center gap-2">
              <span className={`text-[10px] font-black uppercase tracking-[0.4em] ${draft.status === 'confirmed' ? 'text-green-400' : 'text-gold-400'}`}>
                  {statusLabel}
              </span>
            </div>
        </div>
        <div className="absolute top-6 right-8">
           <div className={`w-2.5 h-2.5 rounded-full animate-pulse ${draft.status === 'confirmed' ? 'bg-green-400' : 'bg-gold-400'} shadow-[0_0_15px_rgba(213,182,56,1)]`}></div>
        </div>
      </div>

      <div className="p-10 space-y-8 flex-1 bg-[#FDFCF9] relative overflow-y-auto custom-scrollbar">
        <div className="absolute inset-0 opacity-[0.04] bg-[url('https://www.transparenttextures.com/patterns/natural-paper.png')] pointer-events-none"></div>

        <div className={`transition-all duration-1000 ${draft.guestName ? 'opacity-100' : 'opacity-25'}`}>
          <FieldLabel>Guest Details</FieldLabel>
          <div className={`text-3xl font-serif font-bold text-navy-900 border-b-2 border-stone-200 pb-3 flex flex-col transition-colors ${draft.guestName ? 'border-gold-300' : ''}`}>
            <div className="flex items-baseline gap-3">
              <span className="text-gold-500 text-lg italic">M.</span>
              {draft.guestName || "Awaiting Name..."}
            </div>
            {draft.email && (
              <span className="text-xs font-mono text-stone-400 mt-2 lowercase">{draft.email}</span>
            )}
          </div>
        </div>

        <div className="grid grid-cols-2 gap-10">
          <div className={`transition-all duration-700 delay-100 ${draft.checkIn ? 'opacity-100 scale-100' : 'opacity-25 scale-95'}`}>
            <FieldLabel>Check-In</FieldLabel>
            <div className="font-bold text-navy-900 text-lg flex items-center gap-3">
               <span className="text-gold-500 text-xl">🗓</span> {draft.checkIn || "Pending..."}
            </div>
          </div>
          <div className={`transition-all duration-700 delay-200 ${draft.checkOut ? 'opacity-100 scale-100' : 'opacity-25 scale-95'}`}>
            <FieldLabel>Check-Out</FieldLabel>
            <div className="font-bold text-navy-900 text-lg flex items-center gap-3">
               <span className="text-gold-500 text-xl">🗓</span> {draft.checkOut || "Pending..."}
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-10">
          <div className={`bg-white p-6 rounded-3xl border border-stone-200 shadow-sm transition-all duration-1000 delay-300 ${draft.roomType ? 'opacity-100 translate-y-0 border-gold-200' : 'opacity-30 translate-y-4'}`}>
            <FieldLabel>Room Type</FieldLabel>
            <div className="text-navy-950 font-serif font-bold text-lg leading-tight">
              {draft.roomType || "Selecting..."}
            </div>
          </div>
          <div className={`bg-white p-6 rounded-3xl border border-stone-200 shadow-sm transition-all duration-1000 delay-300 ${draft.guests ? 'opacity-100 translate-y-0 border-gold-200' : 'opacity-30 translate-y-4'}`}>
            <FieldLabel>Guest Count</FieldLabel>
            <div className="text-navy-950 font-serif font-bold text-lg flex items-center gap-2">
              <span className="text-xl">👥</span> {draft.guests || "0"}
            </div>
          </div>
        </div>

        <div className="pt-8 border-t-2 border-dashed border-stone-300 space-y-2">
            <div className="flex justify-between items-center text-[10px] font-black uppercase tracking-widest text-stone-400">
              <span>Subtotal</span>
              <span>${draft.subtotal?.toLocaleString() || 0}</span>
            </div>
            <div className="flex justify-between items-center text-[10px] font-black uppercase tracking-widest text-stone-400">
              <span>Tax (12%)</span>
              <span>${draft.tax?.toLocaleString() || 0}</span>
            </div>
            <div className="flex justify-between items-center pt-2">
                <span className="font-black text-navy-950 text-[11px] uppercase tracking-[0.4em]">Total Balance</span>
                <div className={`font-serif font-bold text-5xl text-gold-600 transition-all duration-1000 ${draft.total ? 'opacity-100 scale-100' : 'opacity-20 scale-90'}`}>
                    ${draft.total?.toLocaleString() || 0}
                </div>
            </div>
        </div>
      </div>

      <div className="p-8 bg-white border-t border-stone-200">
        {draft.status === 'confirmed' ? (
          <div className="space-y-4 animate-fade-in-up">
            <button 
              onClick={() => setShowPhysical(true)}
              className="w-full bg-gold-500 text-navy-950 font-black py-6 rounded-2xl shadow-2xl flex items-center justify-center gap-4 hover:bg-gold-600 transition-all hover:scale-[1.02] group"
            >
              <span className="text-xl group-hover:scale-125 transition-transform">📜</span>
              <span className="uppercase tracking-[0.3em] text-[10px]">Print Physical Confirmation</span>
            </button>
            <p className="text-[9px] text-center text-stone-400 font-bold uppercase tracking-widest">Residency Secured & Recorded</p>
          </div>
        ) : (
          <div className="w-full bg-stone-50 border border-stone-100 text-stone-400 py-6 px-8 rounded-2xl flex items-center justify-between">
             <div className="flex flex-col">
               <span className="text-[9px] uppercase font-black tracking-[0.3em] mb-1">Status</span>
               <span className="text-[10px] font-bold text-stone-600">
                {isComplete ? 'Awaiting Guest Confirmation...' : 'Synchronizing Data...'}
               </span>
             </div>
             <div className="flex gap-1.5 items-center">
                <span className="w-1.5 h-1.5 bg-gold-400 rounded-full animate-bounce [animation-delay:0s]"></span>
                <span className="w-1.5 h-1.5 bg-gold-400 rounded-full animate-bounce [animation-delay:0.2s]"></span>
                <span className="w-1.5 h-1.5 bg-gold-400 rounded-full animate-bounce [animation-delay:0.4s]"></span>
             </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default LiveBookingPanel;